### ISSUE TITLE
Support eslint flat-config

### ISSUE THREAD

**Issue by GNRSN** [storybookjs/eslint-plugin-storybook#140] opened 2023-09-02 06:33 UTC
**Is your feature request related to a problem? Please describe.**
We're opting in to the new eslint flat config which includes many benefits, for our case especially as it allows extending lint-configs in a monorepo without having to install the plugins everywhere. Something which previously required [a patch from Microsoft rushstack](https://www.npmjs.com/package/@rushstack/eslint-patch)

**Describe the solution you'd like**
For `eslint-plugin-storybook` to offer flat-config versions of the included configs, e.g. `recommended` and `csf-strict`

**Describe alternatives you've considered**
I am currently re-mapping the properties of the configs to work with the flat-config object/array, but this might break with any new version os `eslint-plugin-storybook`

**Additional context**
See [the eslint documentation](https://eslint.org/docs/latest/use/configure/configuration-files-new ) for info about flat config. The feature has been in development preview since last year and is now considered stable. From my understanding it will *soon* be the new standard moving forward.

**Comment by osmestad** [comment] 2023-09-26 11:37
Duplicate of #135 I think?

**Comment by yannbf** [comment] 2024-06-21 07:32
Closing as duplicate

**Closed by yannbf** 2024-06-21 07:32 UTC
